### ISSUE TITLE
[VS Code] Add support to build, test and deploy Cell file from VS Code

### ISSUE THREAD

**Issue by nadundesilva** [wso2-cellery/cellery-tooling#6]
**Description:**
Currently the user can build. run and test Cell files by going through the normal CLI flows. However, it would be useful to provide the ability to quickly build, run and test Cell files directly from VS Code itself for improving the development cycles.

**Approach:**
VS Code commands needs to be added to build, run and test the currently open Cell file from VS Code itself.

**Tasks:**
- [ ] Add VS Code Build, Run and Test commands
- [ ] Add support to remember the previous inputs given by the user and provide them as Quick Pick
- [ ] Update logs command to support only showing component logs
- [ ] Check the possibility of tailing logs (since logs are shown right after the instance is started)
- [ ] Add component name prefix to the logs
